# Generated by Django 3.0.8 on 2021-07-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210730_2113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followerandfollowee',
            unique_together={('follower', 'followee')},
        ),
    ]
